# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  j1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Echo environment
        run: echo dev ${{ job.environment.name }}
  j2:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Echo environment
        run: echo test  ${{ job.environment.name }}
  j3:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo environment
        run: echo test  ${{ job.environment.name }}
